on:
  workflow_run:
    workflows: 
      - Tests
    branches:
      - main
    types: 
      - completed

jobs:
  upload_files:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: main
    runs-on: ubuntu-latest
    name: Upload viz files
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Get latest
        run: bash get_latest.sh
      - name: Test dataset
        run: python3 preprocess/test_data.py website/data.csv
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './website'
          remotePath: './incomegaps.com'
