name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: bash install_browser.sh
      - name: Compile with Grunt
        uses: elstudio/actions-js-build/build@v4
  data:
    runs-on: ubuntu-latest
    name: Test update data
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Get latest
        run: bash get_latest.sh
      - name: Make median
        uses: bash make_median.sh
