on:
  pull_request:
    branches:
      - main

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Compile with Grunt
        uses: elstudio/actions-js-build/build@v4
